### ISSUE TITLE
Insurance Objects

### ISSUE THREAD

**Issue by tobyCurtis** [Vchalem/fsc-demo-pack#16]
Hello,

I had first tried to install FSC in my scratch org from the package listed on a Salesforce Help document. I got an error, and found your solution. I ran through it, and I am still getting the same error when the first package is trying to be installed into the scratch org. It is apparently looking for an InsurancePolicy and a Claim object, which do not exist in my scratch org.

Here is the error:
```
Installation errors: 
1) (Alert__c.Claim__c) referenceTo value of 'Claim' does not resolve to a valid sObject type, Details: Alert__c.Claim__c: referenceTo value of 'Claim' does not resolve to a valid sObject type
2) (Alert__c.Insurance_Policy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, Details: Alert__c.Insurance_Policy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type
3) (BillingStatement__c.InsurancePolicy__c) referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type, Details: BillingStatement__c.InsurancePolicy__c: referenceTo value of 'InsurancePolicy' does not resolve to a valid sObject type
```

I see this object was added in the Summer '19 release notes: https://releasenotes.docs.salesforce.com/en-us/summer19/release-notes/rn_fsc.htm

And I also noticed that this repo has been updated since then. Is there something I am missing? Like perhaps a feature that should be in the scratch org definition file to add in these new standard insurance objects?

Thanks very much

**Comment by tobyCurtis** [comment]
It looks like I was indeed missing a scratch org configuration variable!
I added `FinancialServicesUser:10` to my features, and then the objects were in the scratch org.

**Comment by tobyCurtis** [comment]
I should actually add a pull request that fixes this... I will work on that

**Comment by Vchalem** [comment]
Hi Toby! thanks, have you tried the scratch org snapshot pilot? You may be
able to use a snapshot to configure the missing pieces for insurance?

best,
Vanessa

**Comment by tobyCurtis** [comment]
Thanks for the response, Vanessa. 

I actually did not have access to the org with the Insurance objects, it was a clients org and I was trying to reproduce a bug they were seeing without getting access to their org.

But adding the aforementioned  `FinancialServicesUser:10` feature to the `project-scratch-def.json` file totally did the trick.

Thanks,
Toby

**Comment by Vchalem** [comment]
oh great!!
